package com.learn.pojo;

public class TOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.orderno
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    private Integer orderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.prodno
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    private String prodno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.stat
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    private String stat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.o_date
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    private String oDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.m_date
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    private String mDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.orderno
     *
     * @return the value of t_order.orderno
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    public Integer getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.orderno
     *
     * @param orderno the value for t_order.orderno
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    public void setOrderno(Integer orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.prodno
     *
     * @return the value of t_order.prodno
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    public String getProdno() {
        return prodno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.prodno
     *
     * @param prodno the value for t_order.prodno
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    public void setProdno(String prodno) {
        this.prodno = prodno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.stat
     *
     * @return the value of t_order.stat
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.stat
     *
     * @param stat the value for t_order.stat
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    public void setStat(String stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.o_date
     *
     * @return the value of t_order.o_date
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    public String getoDate() {
        return oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.o_date
     *
     * @param oDate the value for t_order.o_date
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    public void setoDate(String oDate) {
        this.oDate = oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.m_date
     *
     * @return the value of t_order.m_date
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    public String getmDate() {
        return mDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.m_date
     *
     * @param mDate the value for t_order.m_date
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    public void setmDate(String mDate) {
        this.mDate = mDate;
    }
}