package com.learn.mapper;

import com.learn.pojo.TOrder;
import java.util.List;

public interface TOrderMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    int deleteByPrimaryKey(Integer orderno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    int insert(TOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    TOrder selectByPrimaryKey(Integer orderno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    List<TOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu May 27 20:39:07 CST 2021
     */
    int updateByPrimaryKey(TOrder record);
}